[[redirects]]
  from = "https://bigredbanana.com/*"
  to = "https://bigredbanana.in/:splat"
  status = 301
  force = true

[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-sitemap"
